---
- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: ensure trusted key is added
      apt_key: 
        url: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-launchpad-ppa-signing-key.asc'
        state: present
    - name: ensure rabbitmq repositories are added
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main'
        - 'deb-src http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main'
        - 'deb https://dl.bintray.com/rabbitmq/debian focal main'
    - name: ensure package is installed
      apt:
        name: rabbitmq-server
    - name: ensure rabbitmq plugins are installed
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted
- hosts: rabbitmq
  become: yes
  gather_facts: no
  vars:
    user: ads
    password: wtucpDXEE8_@mxGrNs4*
  tasks:
    - name: ensure rabbitmq user is present
      rabbitmq_user: 
        user: '{{ user }}'
        password: '{{ password }}'
        node: "rabbit@microservice"
        tags: administrator
        force: yes
        vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        update_password: always
        state: present
    - name: ensure guest user is absent
      rabbitmq_user:
        user: guest
        node: "rabbit@microservice"
        state: absent                             